services:
  valkey:
    image: valkey/valkey:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./data/valkey:/data
  apod-nasa-api:
    build:
      context: ./apod_api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
