/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/apod": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get astronomy picture of the day */
        get: operations["get_apod"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/astros": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get astronauts currently in space */
        get: operations["get_astros"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check server health
         * @description This endpoint just reutrns 'ok'
         */
        get: operations["get_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/mars_weather": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get weather on mars */
        get: operations["get_mars_weather"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiRes: {
            message: string;
            /** Format: int32 */
            number: number;
            people: components["schemas"]["Astros"][];
        };
        Astros: {
            craft: string;
            name: string;
        };
        DirectionData: {
            /** Format: double */
            compass_degrees: number;
            compass_point: string;
            /** Format: double */
            compass_right: number;
            /** Format: double */
            compass_up: number;
            /** Format: int32 */
            ct: number;
        };
        MarsWeatherResponse: {
            sols: {
                [key: string]: components["schemas"]["SolData"];
            };
        };
        Measurement: {
            /** Format: double */
            av: number;
            /** Format: int32 */
            ct: number;
            /** Format: double */
            mn: number;
            /** Format: double */
            mx: number;
        };
        Res: {
            explanation: string;
            hdurl: string;
            title: string;
        };
        SolData: {
            AT?: null | components["schemas"]["Measurement"];
            First_UTC: string;
            HWS?: null | components["schemas"]["Measurement"];
            Last_UTC: string;
            /** Format: int32 */
            Month_ordinal: number;
            Northern_season: string;
            PRE?: null | components["schemas"]["Measurement"];
            Season: string;
            Southern_season: string;
            WD?: null | components["schemas"]["WindDirection"];
        };
        WindDirection: {
            most_common: components["schemas"]["DirectionData"];
        } & {
            [key: string]: components["schemas"]["DirectionData"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_apod: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Res"];
                };
            };
        };
    };
    get_astros: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiRes"];
                };
            };
        };
    };
    get_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
        };
    };
    get_mars_weather: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Success */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarsWeatherResponse"];
                };
            };
        };
    };
}
